
"""
Scrapers Module for Ghostwriter API

This module contains various web scraping functions to extract data from different platforms.
Each scraper is designed to collect specific data for use in content generation and analysis.
"""

import requests
import os
from typing import Dict, List, Optional, Union, Any


# ----------------------
# LinkedIn Scraper
# ----------------------

def scrape_linkedin_posts(profile_url: str, max_posts: int = 50) -> List[Dict[str, Any]]:
    """
    Scrape recent posts from a LinkedIn profile.
    
    Args:
        profile_url: URL of the LinkedIn profile to scrape posts from
        max_posts: Maximum number of posts to retrieve
        
    Returns:
        List of dictionaries containing post data:
        - Post content
        - Post date
        - Engagement metrics (likes, comments, shares)
        - Media attachments
    """
    APIFY_API_TOKEN = os.environ.get("APIFY_API_TOKEN")
    if not APIFY_API_TOKEN:
        raise Exception("APIFY_API_TOKEN not configured in environment")
    
    print(f"Scraping LinkedIn posts from: {profile_url} (max: {max_posts})")
    
    # Prepare API request
    url = "https://api.apify.com/v2/actor-tasks/james-3rdbrain~ghostwriter-linkedin-posts-scraper/run-sync-get-dataset-items"
    
    headers = {
        "Content-Type": "application/json",
        "Accept": "application/json",
        "Authorization": f"Bearer {APIFY_API_TOKEN}"
    }
    
    payload = {
        "limit": max_posts,
        "username": profile_url
    }
    
    try:
        print(f"Sending request to Apify with payload: {payload}")
        response = requests.post(url, headers=headers, json=payload)
        response.raise_for_status()
        
        result = response.json()
        print(f"LinkedIn scraping successful: Retrieved {len(result) if isinstance(result, list) else 0} posts")
        
        return result
    except requests.exceptions.RequestException as e:
        print(f"LinkedIn scraping failed: {str(e)}")
        if hasattr(e.response, 'text'):
            print(f"Error response: {e.response.text}")
        
        return [{
            "status": "error",
            "message": str(e),
            "profile_url": profile_url
        }]

# ----------------------
# YouTube Scraper
# ----------------------

def scrape_youtube_videos(
    channel_url: str, 
    max_videos: int = 20, 
    sort_by: str = "POPULAR"
) -> List[Dict[str, Any]]:
    """
    Scrape videos and their transcripts from a YouTube channel using Apify API.
    
    Args:
        channel_url: URL of the YouTube channel to scrape videos from
        max_videos: Maximum number of videos to retrieve (default: 50)
        sort_by: How to sort videos - "POPULAR" or "NEWEST" (default: "POPULAR")
        
    Returns:
        List of dictionaries containing comprehensive video data including transcripts
    """
    APIFY_API_TOKEN = os.environ.get("APIFY_API_TOKEN")
    if not APIFY_API_TOKEN:
        raise Exception("APIFY_API_TOKEN not configured in environment")
    
    if sort_by not in ["POPULAR", "NEWEST"]:
        raise ValueError("sort_by must be either 'POPULAR' or 'NEWEST'")
    
    print(f"Scraping YouTube videos from: {channel_url}")
    print(f"Max videos: {max_videos}")
    print(f"Sort by: {sort_by}")
    
    # Prepare API request
    url = "https://api.apify.com/v2/actor-tasks/james-3rdbrain~ghostwriter-youtube-channel-transcript-scraper/run-sync-get-dataset-items"
    
    headers = {
        "Content-Type": "application/json",
        "Accept": "application/json",
        "Authorization": f"Bearer {APIFY_API_TOKEN}"
    }
    
    payload = {
        "downloadSubtitles": True,
        "hasCC": False,
        "hasLocation": False,
        "hasSubtitles": False,
        "is360": False,
        "is3D": False,
        "is4K": False,
        "isBought": False,
        "isHD": False,
        "isHDR": False,
        "isLive": False,
        "isVR180": False,
        "maxResultStreams": 0,
        "maxResults": max_videos,
        "maxResultsShorts": 0,
        "preferAutoGeneratedSubtitles": True,
        "saveSubsToKVS": True,
        "sortVideosBy": sort_by,
        "startUrls": [
            {
                "url": channel_url,
                "method": "GET"
            }
        ],
        "subtitlesFormat": "plaintext",
        "subtitlesLanguage": "en"
    }
    
    try:
        print(f"Sending request to Apify with payload: {payload}")
        response = requests.post(url, headers=headers, json=payload)
        response.raise_for_status()
        
        result = response.json()
        videos_count = len(result) if isinstance(result, list) else 0
        print(f"YouTube scraping successful: Retrieved {videos_count} videos with transcripts")
        
        return result
    except requests.exceptions.RequestException as e:
        print(f"YouTube scraping failed: {str(e)}")
        if hasattr(e, 'response') and e.response is not None:
            print(f"Error response: {e.response.text}")
        
        return [{
            "status": "error",
            "message": str(e),
            "channel_url": channel_url
        }]

def scrape_youtube_single_video(video_url: str) -> Dict[str, Any]:
    """
    Extract the transcript from a YouTube video.
    
    Args:
        video_url: URL of the YouTube video to extract transcript from
        
    Returns:
        Dictionary containing transcript data:
        - Full transcript text
        - Transcript segments with timestamps
        - Video metadata
    """
    APIFY_API_TOKEN = os.environ.get("APIFY_API_TOKEN")
    if not APIFY_API_TOKEN:
        raise Exception("APIFY_API_TOKEN not configured in environment")
    
    print(f"Extracting transcript from YouTube video: {video_url}")
    
    # Prepare API request for a single video
    url = "https://api.apify.com/v2/actor-tasks/james-3rdbrain~ghostwriter-youtube-channel-transcript-scraper/run-sync-get-dataset-items"
    
    headers = {
        "Content-Type": "application/json",
        "Accept": "application/json",
        "Authorization": f"Bearer {APIFY_API_TOKEN}"
    }
    
    payload = {
        "downloadSubtitles": True,
        "hasCC": False,
        "hasLocation": False,
        "hasSubtitles": False,
        "is360": False,
        "is3D": False,
        "is4K": False,
        "isBought": False,
        "isHD": False,
        "isHDR": False,
        "isLive": False,
        "isVR180": False,
        "maxResultStreams": 0,
        "maxResults": 1,
        "maxResultsShorts": 0,
        "preferAutoGeneratedSubtitles": True,
        "saveSubsToKVS": True,
        "sortVideosBy": "NEWEST",
        "startUrls": [
            {
                "url": video_url,
                "method": "GET"
            }
        ],
        "subtitlesFormat": "plaintext",
        "subtitlesLanguage": "en"
    }
    
    try:
        print(f"Sending request to Apify for video transcript: {video_url}")
        response = requests.post(url, headers=headers, json=payload)
        response.raise_for_status()
        
        results = response.json()
        
        # Check if we got results
        if not results or not isinstance(results, list) or len(results) == 0:
            return {
                "status": "error",
                "message": "No transcript data found",
                "video_url": video_url
            }
        
        # Return the first (and only) result
        print(f"Successfully retrieved transcript for: {video_url}")
        return results[0]
    
    except requests.exceptions.RequestException as e:
        print(f"Failed to extract YouTube transcript: {str(e)}")
        if hasattr(e, 'response') and e.response is not None:
            print(f"Error response: {e.response.text}")
        
        return {
            "status": "error",
            "message": str(e),
            "video_url": video_url
        }