import httpx

from app.config import settings

ACTOR_TASK_URL = "https://api.apify.com/v2/actor-tasks/james-3rdbrain~ghostwriter-youtube-channel-transcript-scraper/run-sync-get-dataset-items"


async def fetch_youtube_channel(
    channel_url: str, max_videos: int = 20, sort_by: str = "POPULAR"
) -> list[dict]:
    async with httpx.AsyncClient(timeout=300) as client:
        resp = await client.post(
            ACTOR_TASK_URL,
            headers={
                "Content-Type": "application/json",
                "Accept": "application/json",
                "Authorization": f"Bearer {settings.apify_api_token}",
            },
            json={
                "downloadSubtitles": True,
                "preferAutoGeneratedSubtitles": True,
                "saveSubsToKVS": True,
                "subtitlesFormat": "plaintext",
                "subtitlesLanguage": "en",
                "sortVideosBy": sort_by,
                "maxResults": max_videos,
                "maxResultStreams": 0,
                "maxResultsShorts": 0,
                "startUrls": [{"url": channel_url, "method": "GET"}],
                "hasCC": False,
                "hasLocation": False,
                "hasSubtitles": False,
                "is360": False,
                "is3D": False,
                "is4K": False,
                "isBought": False,
                "isHD": False,
                "isHDR": False,
                "isLive": False,
                "isVR180": False,
            },
        )
        resp.raise_for_status()
        return resp.json()


async def fetch_youtube_video(video_url: str) -> dict | None:
    async with httpx.AsyncClient(timeout=300) as client:
        resp = await client.post(
            ACTOR_TASK_URL,
            headers={
                "Content-Type": "application/json",
                "Accept": "application/json",
                "Authorization": f"Bearer {settings.apify_api_token}",
            },
            json={
                "downloadSubtitles": True,
                "preferAutoGeneratedSubtitles": True,
                "saveSubsToKVS": True,
                "subtitlesFormat": "plaintext",
                "subtitlesLanguage": "en",
                "sortVideosBy": "NEWEST",
                "maxResults": 1,
                "maxResultStreams": 0,
                "maxResultsShorts": 0,
                "startUrls": [{"url": video_url, "method": "GET"}],
                "hasCC": False,
                "hasLocation": False,
                "hasSubtitles": False,
                "is360": False,
                "is3D": False,
                "is4K": False,
                "isBought": False,
                "isHD": False,
                "isHDR": False,
                "isLive": False,
                "isVR180": False,
            },
        )
        resp.raise_for_status()
        results = resp.json()
        return results[0] if results else None
