import httpx
from fastapi import HTTPException

from app.config import settings


def _require_apify_token():
    if not settings.apify_api_token:
        raise HTTPException(
            status_code=503,
            detail="Scraping requires APIFY_API_TOKEN to be configured",
        )


def _actor_url() -> str:
    actor_id = settings.apify_youtube_actor_id
    return f"https://api.apify.com/v2/acts/{actor_id}/run-sync-get-dataset-items"


async def fetch_youtube_channel(
    channel_url: str, max_videos: int = 20, sort_by: str = "POPULAR"
) -> list[dict]:
    _require_apify_token()
    async with httpx.AsyncClient(timeout=300) as client:
        resp = await client.post(
            _actor_url(),
            params={"token": settings.apify_api_token},
            json={
                "downloadSubtitles": True,
                "preferAutoGeneratedSubtitles": True,
                "saveSubsToKVS": True,
                "subtitlesFormat": "plaintext",
                "subtitlesLanguage": "en",
                "sortVideosBy": sort_by,
                "maxResults": max_videos,
                "maxResultStreams": 0,
                "maxResultsShorts": 0,
                "startUrls": [{"url": channel_url, "method": "GET"}],
                "hasCC": False,
                "hasLocation": False,
                "hasSubtitles": False,
                "is360": False,
                "is3D": False,
                "is4K": False,
                "isBought": False,
                "isHD": False,
                "isHDR": False,
                "isLive": False,
                "isVR180": False,
            },
        )
        resp.raise_for_status()
        return resp.json()


async def fetch_youtube_video(video_url: str) -> dict | None:
    _require_apify_token()
    async with httpx.AsyncClient(timeout=300) as client:
        resp = await client.post(
            _actor_url(),
            params={"token": settings.apify_api_token},
            json={
                "downloadSubtitles": True,
                "preferAutoGeneratedSubtitles": True,
                "saveSubsToKVS": True,
                "subtitlesFormat": "plaintext",
                "subtitlesLanguage": "en",
                "sortVideosBy": "NEWEST",
                "maxResults": 1,
                "maxResultStreams": 0,
                "maxResultsShorts": 0,
                "startUrls": [{"url": video_url, "method": "GET"}],
                "hasCC": False,
                "hasLocation": False,
                "hasSubtitles": False,
                "is360": False,
                "is3D": False,
                "is4K": False,
                "isBought": False,
                "isHD": False,
                "isHDR": False,
                "isLive": False,
                "isVR180": False,
            },
        )
        resp.raise_for_status()
        results = resp.json()
        return results[0] if results else None
